services:
  - type: web
    name: transErp
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false   # lo pones en el dashboard de Render
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        fromService:
          type: web
          name: transErp
          property: host
